const books = [
  { title: "The City We Became", author: "N. K. Jemisin", tags: ["fantasy", "fiction", "afrofuturism", "science fiction", "sci-fi"] },
  { title: "The Catcher in the Rye", author: "J. D. Salinger", tags: ["fiction", "young adult", "YA", "realism", "coming of age", "classic"] },
  { title: "The Hundred Thousand Kingdoms", author: "N. K. Jemisin", tags: ["fantasy", "fiction", "adventure", "series"] },
  { title: "Sapiens: A Brief History of Humankind", author: "Yuval Noah Harari", tags: ["nonfiction", "history", "anthropology", "science", "sociology"] },
  { title: "Behave: The Biology of Humans at Our Best and Worst", author: "Robert M. Sapolsky", tags: ["nonfiction", "anthropology", "science", "sociology", "biology"] },
  { title: "The Parable of the Talents", author: "Octavia Butler", tags: ["fiction", "dystopian", "science fiction"] },
  { title: "1984", author: "George Orwell", tags: ["fiction", "dystopian", "science fiction", "classics", "adult"] },
  { title: "Remarkably Bright Creatures", author: "Shelby Van Pelt", tags: ["fiction", "mystery", "magical realism"] },
  { title: "Crying in H Mart", author: "Michelle Zauner", tags: ["memoir", "nonfiction", "autobiography"] },
  { title: "Wild: From Lost to Found on the Pacific Crest Trail", author: "Cheryl Strayed", tags: ["nonfiction", "memoir", "adventure", "travel"] },
  { title: "To Kill a Mockingbird", author: "Harper Lee", tags: ["fiction", "classic", "literature"] },
  { title: "Pride and Prejudice", author: "Jane Austen", tags: ["fiction", "classic", "romance"] },
  { title: "The Great Gatsby", author: "F. Scott Fitzgerald", tags: ["fiction", "classic", "literature"] },
  { title: "Moby-Dick", author: "Herman Melville", tags: ["fiction", "classic", "adventure"] },
  { title: "Jane Eyre", author: "Charlotte Brontë", tags: ["fiction", "classic", "romance"] },
  { title: "The Catcher in the Rye", author: "J.D. Salinger", tags: ["fiction", "classic", "young adult"] },
  { title: "Lord of the Flies", author: "William Golding", tags: ["fiction", "classic", "dystopian"] },
  { title: "The Hobbit", author: "J.R.R. Tolkien", tags: ["fantasy", "fiction", "adventure"] },
  { title: "The Lord of the Rings", author: "J.R.R. Tolkien", tags: ["fantasy", "fiction", "adventure"] },
  { title: "Harry Potter and the Sorcerer's Stone", author: "J.K. Rowling", tags: ["fantasy", "fiction", "young adult"] },
  
  { title: "The Da Vinci Code", author: "Dan Brown", tags: ["thriller", "mystery", "fiction"] },
  { title: "Angels & Demons", author: "Dan Brown", tags: ["thriller", "mystery", "fiction"] },
  { title: "Gone Girl", author: "Gillian Flynn", tags: ["thriller", "mystery", "fiction"] },
  { title: "The Girl with the Dragon Tattoo", author: "Stieg Larsson", tags: ["thriller", "mystery", "fiction"] },
  { title: "A Game of Thrones", author: "George R.R. Martin", tags: ["fantasy", "fiction", "adventure"] },
  { title: "Dune", author: "Frank Herbert", tags: ["sci-fi", "fiction", "classic"] },
  { title: "Neuromancer", author: "William Gibson", tags: ["sci-fi", "fiction", "cyberpunk"] },
  { title: "Brave New World", author: "Aldous Huxley", tags: ["sci-fi", "dystopian", "classic"] },
  { title: "Fahrenheit 451", author: "Ray Bradbury", tags: ["sci-fi", "dystopian", "classic"] },
  { title: "Ender's Game", author: "Orson Scott Card", tags: ["sci-fi", "fiction", "classic"] },
  
  { title: "The Shining", author: "Stephen King", tags: ["horror", "fiction", "thriller"] },
  { title: "It", author: "Stephen King", tags: ["horror", "fiction", "thriller"] },
  { title: "Misery", author: "Stephen King", tags: ["horror", "fiction", "thriller"] },
  { title: "Dracula", author: "Bram Stoker", tags: ["horror", "classic", "fiction"] },
  { title: "Frankenstein", author: "Mary Shelley", tags: ["horror", "classic", "fiction"] },
  { title: "The Road", author: "Cormac McCarthy", tags: ["fiction", "dystopian", "classic"] },
  { title: "The Goldfinch", author: "Donna Tartt", tags: ["fiction", "literature", "mystery"] },
  { title: "Big Little Lies", author: "Liane Moriarty", tags: ["fiction", "mystery", "thriller"] },
  { title: "Little Fires Everywhere", author: "Celeste Ng", tags: ["fiction", "literature", "mystery"] },
  { title: "Normal People", author: "Sally Rooney", tags: ["fiction", "literature", "romance"] },
  
  { title: "The Silent Patient", author: "Alex Michaelides", tags: ["thriller", "mystery", "fiction"] },
  { title: "Where the Crawdads Sing", author: "Delia Owens", tags: ["fiction", "mystery", "literature"] },
  { title: "Educated", author: "Tara Westover", tags: ["memoir", "nonfiction", "autobiography"] },
  { title: "Becoming", author: "Michelle Obama", tags: ["memoir", "nonfiction", "autobiography"] },
  { title: "The Immortal Life of Henrietta Lacks", author: "Rebecca Skloot", tags: ["nonfiction", "biography", "science"] },
  { title: "The Wright Brothers", author: "David McCullough", tags: ["nonfiction", "biography", "history"] },
  { title: "The Glass Castle", author: "Jeannette Walls", tags: ["memoir", "nonfiction", "autobiography"] },
  { title: "When Breath Becomes Air", author: "Paul Kalanithi", tags: ["memoir", "nonfiction", "autobiography"] },
  { title: "Into the Wild", author: "Jon Krakauer", tags: ["nonfiction", "adventure", "biography"] },
  { title: "Into Thin Air", author: "Jon Krakauer", tags: ["nonfiction", "adventure", "biography"] },
  
  { title: "Born a Crime", author: "Trevor Noah", tags: ["memoir", "nonfiction", "autobiography"] },
  { title: "The Life-Changing Magic of Tidying Up", author: "Marie Kondo", tags: ["nonfiction", "self-help", "organization"] },
  { title: "Atomic Habits", author: "James Clear", tags: ["nonfiction", "self-help", "personal development"] },
  { title: "The Subtle Art of Not Giving a F*ck", author: "Mark Manson", tags: ["nonfiction", "self-help", "personal development"] },
  { title: "You Are a Badass", author: "Jen Sincero", tags: ["nonfiction", "self-help", "personal development"] },
  { title: "Start with Why", author: "Simon Sinek", tags: ["nonfiction", "self-help", "business"] },
  { title: "The 7 Habits of Highly Effective People", author: "Stephen R. Covey", tags: ["nonfiction", "self-help", "personal development"] },
  { title: "Rich Dad Poor Dad", author: "Robert T. Kiyosaki", tags: ["nonfiction", "finance", "self-help"] },
  { title: "The Millionaire Next Door", author: "Thomas J. Stanley", tags: ["nonfiction", "finance", "self-help"] },
  { title: "Principles: Life and Work", author: "Ray Dalio", tags: ["nonfiction", "business", "self-help"] },
  
  { title: "Daring Greatly", author: "Brené Brown", tags: ["nonfiction", "self-help", "personal development"] },
  { title: "Quiet: The Power of Introverts in a World That Can't Stop Talking", author: "Susan Cain", tags: ["nonfiction", "self-help", "psychology"] },
  { title: "Thinking, Fast and Slow", author: "Daniel Kahneman", tags: ["nonfiction", "psychology", "behavioral science"] },
  { title: "Sapiens: A Brief History of Humankind", author: "Yuval Noah Harari", tags: ["nonfiction", "history", "philosophy"] },
  { title: "The Code Breaker", author: "Walter Isaacson", tags: ["nonfiction", "biography", "science"] },
  { title: "The Undoing Project", author: "Michael Lewis", tags: ["nonfiction", "psychology", "behavioral science"] },
  { title: "The Power of Habit", author: "Charles Duhigg", tags: ["nonfiction", "self-help", "psychology"] },
  { title: "The Four Agreements", author: "Don Miguel Ruiz", tags: ["nonfiction", "self-help", "spirituality"] },
  { title: "The Alchemist", author: "Paulo Coelho", tags: ["fiction", "adventure", "philosophy"] },
  { title: "The Prophet", author: "Khalil Gibran", tags: ["fiction", "poetry", "philosophy"] },
  
  { title: "The Art of War", author: "Sun Tzu", tags: ["nonfiction", "military", "philosophy"] },
  { title: "The Prince", author: "Niccolò Machiavelli", tags: ["nonfiction", "politics", "philosophy"] },
  { title: "Meditations", author: "Marcus Aurelius", tags: ["nonfiction", "philosophy", "self-help"] },
  { title: "The Tao Te Ching", author: "Laozi", tags: ["nonfiction", "philosophy", "spirituality"] },
  { title: "The Bhagavad Gita", author: "Anonymous", tags: ["nonfiction", "philosophy", "spirituality"] },
  { title: "The Koran", author: "Anonymous", tags: ["nonfiction", "religion", "philosophy"] },
  { title: "The Bible", author: "Various Authors", tags: ["nonfiction", "religion", "philosophy"] },
  { title: "The Hitchhiker's Guide to the Galaxy", author: "Douglas Adams", tags: ["sci-fi", "comedy", "fiction"] },
  { title: "Slaughterhouse-Five", author: "Kurt Vonnegut", tags: ["sci-fi", "fiction", "classic"] },
  { title: "Catch-22", author: "Joseph Heller", tags: ["fiction", "classic", "satire"] },

  { title: "The Name of the Wind", author: "Patrick Rothfuss", tags: ["fantasy", "fiction", "adventure"] },
  { title: "The Wise Man's Fear", author: "Patrick Rothfuss", tags: ["fantasy", "fiction", "adventure"] },
  { title: "The Way of Kings", author: "Brandon Sanderson", tags: ["fantasy", "fiction", "epic"] },
  { title: "Mistborn: The Final Empire", author: "Brandon Sanderson", tags: ["fantasy", "fiction", "epic"] },
  { title: "The Black Prism", author: "Brent Weeks", tags: ["fantasy", "fiction", "epic"] },
  { title: "The Shadow of the Wind", author: "Carlos Ruiz Zafón", tags: ["fiction", "mystery", "literature"] },
  { title: "The Book Thief", author: "Markus Zusak", tags: ["fiction", "historical", "literature"] },
  { title: "All the Light We Cannot See", author: "Anthony Doerr", tags: ["fiction", "historical", "literature"] },
  { title: "Life of Pi", author: "Yann Martel", tags: ["fiction", "adventure", "philosophy"] },
  { title: "The Catcher in the Rye", author: "J.D. Salinger", tags: ["fiction", "classic", "young adult"] }
];
